name: enigma2-plugins build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build enigma2-plugins
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        gcc: [11,13]
        python: ['3.10','3.11','3.12']
    steps:
      - name: Install prerequisites
        run: |
          sudo add-apt-repository -y ppa:deadsnakes/ppa
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get -q update
          sudo apt remove -y libunwind-14-dev
          sudo apt-get install -y g++-${{ matrix.gcc }} build-essential autoconf autotools-dev gettext python${{ matrix.python }}-dev libntirpc-dev
          
      - uses: actions/checkout@v4
        with:
          ref: 'master'

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Build plugins, gcc-${{ matrix.gcc }}, python ${{ matrix.python }}
        env:
          CC: "gcc-${{ matrix.gcc }}"
          CXX: "g++-${{ matrix.gcc }}"
        run: |
          pip3 install six
          sed -i '/PKG_CHECK_MODULES(ENIGMA2, enigma2)/d' ./configure.ac
          sed -i '/PKG_CHECK_MODULES(LIBCRYPTO, libcrypto)/d' ./configure.ac
          sudo ln -s /usr/include/ntirpc/rpc/rpc.h /usr/include/rpc
          sudo ln -s /usr/include/ntirpc/misc/abstract_atomic.h /usr/include/misc/
          sudo ln -s /usr/include/ntirpc/netconfig.h /usr/include/misc/
          sudo ln -s /usr/include/ntirpc/misc/stdio.h /usr/include/misc
          sudo ln -s /usr/include/ntirpc/intrinsic.h /usr/include
          sudo ln -s /usr/include/ntirpc/rpc/tirpc_compat.h /usr/include/rpc
          sudo ln -s /usr/include/ntirpc/rpc/auth.h /usr/include/rpc
          sudo ln -s /usr/include/ntirpc/rpc/rpc_err.h /usr/include/rpc
          sudo ln -s /usr/include/ntirpc/rpc/clnt_stat.h /usr/include/rpc
          sudo ln -s /usr/include/ntirpc/rpc/auth_stat.h /usr/include/rpc
          sudo ln -s /usr/include/ntirpc/rpc/clnt.h /usr/include/rpc
          sudo ln -s /usr/include/ntirpc/misc/rbtree.h /usr/include/misc
          sudo ln -s /usr/include/ntirpc/misc/opr.h /usr/include/misc
          sudo ln -s /usr/include/ntirpc/misc/wait_queue.h /usr/include/misc
          sudo ln -s /usr/include/ntirpc/misc/queue.h /usr/include/misc
          sudo ln -s /usr/include/ntirpc/reentrant.h /usr/include
          sudo ln -s /usr/include/ntirpc/rpc/svc.h /usr/include/rpc
          sudo ln -s /usr/include/ntirpc/rpc/rpc_msg.h /usr/include/rpc
          sudo ln -s /usr/include/ntirpc/rpc/work_pool.h /usr/include/rpc
          sudo ln -s /usr/include/ntirpc/rpc/pool_queue.h /usr/include/rpc
          sudo ln -s /usr/include/ntirpc/misc/portable.h /usr/include/misc
          sudo ln -s /usr/include/ntirpc/misc/timespec.h /usr/include/misc
          sudo ln -s /usr/include/ntirpc/misc/os_epoll.h /usr/include/misc
          sudo ln -s /usr/include/ntirpc/rpc/auth_unix.h /usr/include/rpc
          sudo ln -s /usr/include/ntirpc/rpc/rpcb_clnt.h /usr/include/rpc
          sudo ln -s /usr/include/ntirpc/rpc/rpcb_prot.h /usr/include/rpc
          sudo ln -s /usr/include/ntirpc/rpc/rpcent.h /usr/include/rpc
          autoreconf -i
          ./configure --without-debug --with-po
          make
          rm -rf ./subsdownloader2
          python -m compileall .
